/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import sun.security.util.Password;

/**
 *
 * @author jenif
 */
public class Menu3 extends javax.swing.JFrame {
    private boolean modoOscuro;
    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();

    /**
     * Creates new form Menu
     */
    public Menu3() {

        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
    }

    public void transparenciButton() {
        AgregarClientebtn.setOpaque(false);
        AgregarClientebtn.setContentAreaFilled(false);
        AgregarClientebtn.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        AgregarInsumoConsumobtn.setOpaque(false);
        AgregarInsumoConsumobtn.setContentAreaFilled(false);
        AgregarInsumoConsumobtn.setBorderPainted(false);
        AgregarInsumoUsobtn.setOpaque(false);
        AgregarInsumoUsobtn.setContentAreaFilled(false);
        AgregarInsumoUsobtn.setBorderPainted(false);
        AgregarProveedorbtn.setOpaque(false);
        AgregarProveedorbtn.setContentAreaFilled(false);
        AgregarProveedorbtn.setBorderPainted(false);
        AgregarVentabtn.setOpaque(false);
        AgregarVentabtn.setContentAreaFilled(false);
        AgregarVentabtn.setBorderPainted(false);
        AgregarPerdidabtn.setOpaque(false);
        AgregarPerdidabtn.setContentAreaFilled(false);
        AgregarPerdidabtn.setBorderPainted(false);
        AgregarMateriaPrimabtn.setOpaque(false);
        AgregarMateriaPrimabtn.setContentAreaFilled(false);
        AgregarMateriaPrimabtn.setBorderPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        AgregarClientebtn = new javax.swing.JButton();
        AgregarInsumoUsobtn = new javax.swing.JButton();
        AgregarVentabtn = new javax.swing.JButton();
        AgregarInsumoConsumobtn = new javax.swing.JButton();
        AgregarMateriaPrimabtn = new javax.swing.JButton();
        AgregarPerdidabtn = new javax.swing.JButton();
        AgregarProveedorbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btn_oscuro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        AgregarClientebtn.setBackground(new java.awt.Color(0, 0, 102));
        AgregarClientebtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarClientebtn.setForeground(new java.awt.Color(102, 102, 102));
        AgregarClientebtn.setText("AGREGAR CLIENTE");
        AgregarClientebtn.setBorder(null);
        AgregarClientebtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        AgregarClientebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClientebtnActionPerformed(evt);
            }
        });

        AgregarInsumoUsobtn.setBackground(new java.awt.Color(0, 0, 102));
        AgregarInsumoUsobtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarInsumoUsobtn.setForeground(new java.awt.Color(102, 102, 102));
        AgregarInsumoUsobtn.setText("AGREGAR INSUMO PARA USO");
        AgregarInsumoUsobtn.setBorder(null);
        AgregarInsumoUsobtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        AgregarInsumoUsobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarInsumoUsobtnActionPerformed(evt);
            }
        });

        AgregarVentabtn.setBackground(new java.awt.Color(0, 0, 102));
        AgregarVentabtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarVentabtn.setForeground(new java.awt.Color(102, 102, 102));
        AgregarVentabtn.setText("AGREGAR VENTA");
        AgregarVentabtn.setBorder(null);
        AgregarVentabtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        AgregarVentabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVentabtnActionPerformed(evt);
            }
        });

        AgregarInsumoConsumobtn.setBackground(new java.awt.Color(0, 0, 102));
        AgregarInsumoConsumobtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarInsumoConsumobtn.setForeground(new java.awt.Color(102, 102, 102));
        AgregarInsumoConsumobtn.setText("AGREGAR INSUMO PARA CONSUMO");
        AgregarInsumoConsumobtn.setBorder(null);
        AgregarInsumoConsumobtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        AgregarInsumoConsumobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarInsumoConsumobtnActionPerformed(evt);
            }
        });

        AgregarMateriaPrimabtn.setBackground(new java.awt.Color(0, 0, 102));
        AgregarMateriaPrimabtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarMateriaPrimabtn.setForeground(new java.awt.Color(102, 102, 102));
        AgregarMateriaPrimabtn.setText("AGREGAR MATERIA PRIMA");
        AgregarMateriaPrimabtn.setBorder(null);
        AgregarMateriaPrimabtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        AgregarMateriaPrimabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMateriaPrimabtnActionPerformed(evt);
            }
        });

        AgregarPerdidabtn.setBackground(new java.awt.Color(0, 0, 102));
        AgregarPerdidabtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarPerdidabtn.setForeground(new java.awt.Color(102, 102, 102));
        AgregarPerdidabtn.setText("AGREGAR PERDIDA");
        AgregarPerdidabtn.setBorder(null);
        AgregarPerdidabtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        AgregarPerdidabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPerdidabtnActionPerformed(evt);
            }
        });

        AgregarProveedorbtn.setBackground(new java.awt.Color(0, 0, 102));
        AgregarProveedorbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarProveedorbtn.setForeground(new java.awt.Color(102, 102, 102));
        AgregarProveedorbtn.setText("AGREGAR PROVEEDOR");
        AgregarProveedorbtn.setBorder(null);
        AgregarProveedorbtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        AgregarProveedorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProveedorbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AgregarClientebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgregarInsumoConsumobtn, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(AgregarInsumoUsobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AgregarPerdidabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgregarMateriaPrimabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarVentabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgregarProveedorbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(110, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(AgregarClientebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AgregarInsumoUsobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AgregarInsumoConsumobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AgregarMateriaPrimabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AgregarPerdidabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AgregarProveedorbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(AgregarVentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 600));

        jPanel1.setBackground(new java.awt.Color(242, 253, 250));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_oscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/darkmode_1.png"))); // NOI18N
        btn_oscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oscuroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(947, Short.MAX_VALUE)
                .addComponent(btn_oscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(btn_oscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 569, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarClientebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClientebtnActionPerformed
        // TODO add your handling code here:
        Libreta cliente = new Libreta();
        cliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarClientebtnActionPerformed

    private void AgregarInsumoUsobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarInsumoUsobtnActionPerformed
        // TODO add your handling code here:
        Inventario inventario = new Inventario();
        inventario.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarInsumoUsobtnActionPerformed

    private void AgregarVentabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVentabtnActionPerformed
        // TODO add your handling code here:

        Ventas venta = new Ventas();
        venta.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarVentabtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AgregarInsumoConsumobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarInsumoConsumobtnActionPerformed
        // TODO add your handling code here:
        MedicamentosYAlimentos medicamentosYAlimentos = new MedicamentosYAlimentos();
        medicamentosYAlimentos.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarInsumoConsumobtnActionPerformed

    private void AgregarMateriaPrimabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMateriaPrimabtnActionPerformed
        // TODO add your handling code here:
        MateriaPrima materiaPrima = new MateriaPrima();
        materiaPrima.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarMateriaPrimabtnActionPerformed

    private void AgregarPerdidabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPerdidabtnActionPerformed
        // TODO add your handling code here:
        PerdidaMateriaPrima perdidaMateriaPrima = new PerdidaMateriaPrima();
        perdidaMateriaPrima.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarPerdidabtnActionPerformed

    private void AgregarProveedorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProveedorbtnActionPerformed
        // TODO add your handling code here:
        Proveedor proveedor = new Proveedor();
        proveedor.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarProveedorbtnActionPerformed

    private void btn_oscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oscuroActionPerformed
          if (!modoOscuro) {
            Pintar(Color.decode("#FFFFE0"), "/Imagenes/darkmode_2.png",Color.decode("#2e3951"), Color.decode("#212b41"));

            modoOscuro = true;
        } else if (modoOscuro == true) {
            Pintar(Color.decode("#66646C"), "/Imagenes/darkmode_1.png",Color.WHITE, Color.decode("#F2FDFA"));
            modoOscuro = false;
        }
    }//GEN-LAST:event_btn_oscuroActionPerformed
    private void Pintar(Color colorbotones, String imagen,Color colorbase, Color colorfondo) {
        panel.setPanelBase(jPanel2);
        panel.setColorBase(colorbase);
        panel.getPanelBase();
        panel.setPanelFondo(jPanel1);
        panel.setColorFondo(colorfondo);
        panel.getPanelFondo();
        boton.setBoton(AgregarClientebtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(AgregarInsumoConsumobtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(AgregarInsumoUsobtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(AgregarMateriaPrimabtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(AgregarPerdidabtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(AgregarProveedorbtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(AgregarVentabtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        botonIcon.setBotonActivador(btn_oscuro);
        botonIcon.setNombreimagen(imagen);
        botonIcon.getBotonActivador();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarClientebtn;
    private javax.swing.JButton AgregarInsumoConsumobtn;
    private javax.swing.JButton AgregarInsumoUsobtn;
    private javax.swing.JButton AgregarMateriaPrimabtn;
    private javax.swing.JButton AgregarPerdidabtn;
    private javax.swing.JButton AgregarProveedorbtn;
    private javax.swing.JButton AgregarVentabtn;
    private javax.swing.JButton btn_oscuro;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
